package com.jayemceekay.shadowedhearts.client;

import com.mojang.blaze3d.shaders.Uniform;
import net.minecraft.client.renderer.ShaderInstance;

/**
 * Caches Uniform handles for the SHADOW_AURA_FOG shader to avoid per-frame name lookups.
 * Context: Minecraft Cobblemon mod; all shadow/purity/corruption/capture terms are gameplay mechanics.
 */
public record ShadowFogUniforms(
        Uniform uModel,
        Uniform uInvModel,
        Uniform uView,
        Uniform uProj,
        Uniform uMVP,
        Uniform uInvView,
        Uniform uInvProj,
        Uniform uCameraPosWS,
        Uniform uEntityPosWS,
        Uniform uEntityVelWS,
        Uniform uVelLagWS,
        Uniform uSpeed,
        Uniform uTime,
        Uniform uExpand,
        Uniform uGravityDir,
        Uniform uWindWS,
        Uniform uProxyRadius,
        Uniform uProxyHalfHeight,
        Uniform uAuraFade,
        Uniform uFadeGamma,
        Uniform uDensity,
        Uniform uAbsorption,
        Uniform uRimStrength,
        Uniform uRimPower,
        Uniform uMaxThickness,
        Uniform uThicknessFeather,
        Uniform uEdgeKill,
        Uniform uNoiseScaleRel,
        Uniform uScrollSpeedRel,
        Uniform uLimbSoft,
        Uniform uLimbHardness,
        Uniform uMinPathNorm,
        Uniform uGlowGamma,
        Uniform uBlackPoint,
        Uniform uWarpAmp,
        Uniform uPixelsPerRadius,
        Uniform uPosterizeSteps,
        Uniform uDitherAmount,
        Uniform uPatchScaleRel,
        Uniform uPatchThreshBase,
        Uniform uPatchThreshTop,
        Uniform uPatchSharpness,
        Uniform uPatchGamma,
        Uniform uPatchStrengthTop,
        Uniform uHeightFadeMin,
        Uniform uHeightFadePow,
        Uniform uFieldFreq,
        Uniform uShearK,
        Uniform uBaseAdv,
        Uniform uVelInfluence,
        Uniform uCorePow,
        Uniform uColorA,
        Uniform uColorB,
        Uniform uShadowMix,
        Uniform uShadowKnee,
        Uniform uShadowGamma,
        Uniform uShadowDesat
) {
    public static ShadowFogUniforms from(ShaderInstance sh) {
        if (sh == null) return null;
        return new ShadowFogUniforms(
                sh.getUniform("uModel"),
                sh.getUniform("uInvModel"),
                sh.getUniform("uView"),
                sh.getUniform("uProj"),
                // Some mappings expose safeGetUniform; getUniform(null-safe) is fine — may return null if absent
                sh.getUniform("uMVP"),
                sh.getUniform("uInvView"),
                sh.getUniform("uInvProj"),
                sh.getUniform("uCameraPosWS"),
                sh.getUniform("uEntityPosWS"),
                sh.getUniform("uEntityVelWS"),
                sh.getUniform("uVelLagWS"),
                sh.getUniform("uSpeed"),
                sh.getUniform("uTime"),
                sh.getUniform("uExpand"),
                sh.getUniform("uGravityDir"),
                sh.getUniform("uWindWS"),
                sh.getUniform("uProxyRadius"),
                sh.getUniform("uProxyHalfHeight"),
                sh.getUniform("uAuraFade"),
                sh.getUniform("uFadeGamma"),
                sh.getUniform("uDensity"),
                sh.getUniform("uAbsorption"),
                sh.getUniform("uRimStrength"),
                sh.getUniform("uRimPower"),
                sh.getUniform("uMaxThickness"),
                sh.getUniform("uThicknessFeather"),
                sh.getUniform("uEdgeKill"),
                sh.getUniform("uNoiseScaleRel"),
                sh.getUniform("uScrollSpeedRel"),
                sh.getUniform("uLimbSoft"),
                sh.getUniform("uLimbHardness"),
                sh.getUniform("uMinPathNorm"),
                sh.getUniform("uGlowGamma"),
                sh.getUniform("uBlackPoint"),
                sh.getUniform("uWarpAmp"),
                sh.getUniform("uPixelsPerRadius"),
                sh.getUniform("uPosterizeSteps"),
                sh.getUniform("uDitherAmount"),
                sh.getUniform("uPatchScaleRel"),
                sh.getUniform("uPatchThreshBase"),
                sh.getUniform("uPatchThreshTop"),
                sh.getUniform("uPatchSharpness"),
                sh.getUniform("uPatchGamma"),
                sh.getUniform("uPatchStrengthTop"),
                sh.getUniform("uHeightFadeMin"),
                sh.getUniform("uHeightFadePow"),
                sh.getUniform("uFieldFreq"),
                sh.getUniform("uShearK"),
                sh.getUniform("uBaseAdv"),
                sh.getUniform("uVelInfluence"),
                sh.getUniform("uCorePow"),
                sh.getUniform("uColorA"),
                sh.getUniform("uColorB"),
                sh.getUniform("uShadowMix"),
                sh.getUniform("uShadowKnee"),
                sh.getUniform("uShadowGamma"),
                sh.getUniform("uShadowDesat")
        );
    }
}
